name: Create Release

on:
  push:
    tags:
      - 'release/*.*.*'

permissions:
  contents: write

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # 全履歴を取得して前回のタグとの差分を確認

      - name: Extract version from tag
        id: version
        run: |
          # release/a.b.c から a.b.c を抽出
          VERSION=${GITHUB_REF#refs/tags/release/}
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Create Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create ${{ github.ref_name }} \
            --title "${{ steps.version.outputs.version }}" \
            --generate-notes